### ISSUE TITLE
Code Louisville May2020 Courses to be Completed

### ISSUE THREAD

**Issue by cyadehn** [cyadehn/Treehouse#2]
## TODO:

*Courses left to Complete the Code Lou May 2020 Track*

- [x] Introducing the VS Code Text Editor
- [x] CSS Layout Basics
- [x] Introduction to the Terminal
- [x] Introduction to Git
- [x] GitHub Basics
- [x] Debugging CSS with Chrome DevTools
- [x] Responsive Layouts
- [x] Practice Media Queries
- [x] CSS Flexbox Layout
- [x] HTML Forms
- [x] Practice Basic Variables, Input and Output in JavaScript
- [x] JavaScript Numbers
- [x] JavaScript Functions
- [x] JavaScript Loops, Arrays and Objects
- [x] CSS Selectors
- [x] Web Accessibility Compliance
- [x] Website Optimization

😃
